### ISSUE TITLE
Plugin using yaml despite being configured for MySQL

### ISSUE THREAD

**Issue by krittr** [reosfire/TemporaryWhiteList#10]
My Configuration:
```
#Time between checks if online player become not whitelisted in ticks
SubscriptionEndCheckTicks: 100
#Time to pass between actual-data requests per player. in seconds
#Negative values disables any updates (recommended when data in DataProvider can't be changed by anything other than this plugin)
#0 value enforce plugin to always get actual data (not recommended)
RefreshAfter: 60

#ignore case in nicknames
IgnoreCase: false

#yaml mysql
DataProvider: mysql

#File name to store data about players when DataProvider: yaml
DataFile: "data.yml"

#Data to connect to database when DataProvider: mysql
Mysql:
  Ip: MY HOST
  User: "MY USER"
  Password: "MY PASSWORD"
  Database: "MY DATABASE"
  Table: "WhiteListTable"
  #optional
  Port: 3306
  UseSsl: false
  UseUnicode: true
  AutoReconnect: true
  FailOverReadOnly: false
  MaxReconnects: 2
  MaxConnectionLifetime: 550000

#File in `translations` folder to use
Translation: "en.yml"

#Players per page when used /twl list command
ListPageSize: 4

#Time formats used in placeholders. Pattern docs:
# https://commons.apache.org/proper/commons-lang/javadocs/api-3.0/org/apache/commons/lang3/time/DurationFormatUtils.html
# https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
DurationFormat: "&bdd 'days' &cHH 'hours' &emm 'minutes' &ass 'seconds'"
DateTimeFormat: "[dd MM yyyy] HH:mm:ss"
```

I have tried with both the host url and IP for the database and am still having data stored in YAML.
